// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dquknkhfmsbfxjbknrma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxdWtua2hmbXNiZnhqYmtucm1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MjA3OTcsImV4cCI6MjA2MzA5Njc5N30.ONx5qOHNdfxTQoPe_CMeIZskQyfvREJugLCnPVlR9kg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);